### ISSUE TITLE
Backport a fix for offbrand adapter

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/Ishiiruka#111]
https://github.com/dolphin-emu/dolphin/pull/8933

After some testing, we can confirm that this fixes adapter issues for the main offbrand adapter we deal with (pdobq) and it would be good to try to backport the fix.

**Comment by jroberts2010** [comment]
Looks like this breaks some other adapters (including the 4 port Mayflash)
https://bugs.dolphin-emu.org/issues/12182

**Comment by NikhilNarayana** [comment]
> Looks like this breaks some other adapters (including the 4 port Mayflash)
> https://bugs.dolphin-emu.org/issues/12182

Yeah I've been watching it. We wouldn't merge a fix that isn't compatible with the official and Mayflash adapters.
