### ISSUE TITLE
Seeking past the left end of the seekbar doesn't behave properly

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/Ishiiruka#117]
Issue found on Windows, confirmed on Linux as well so I would expect it to also occur on macOS

If the user drags the seek cursor past the left side of the window, the marker will not update position but the game will load the initial savestate.

**Comment by jordan-zilch** [comment]
I'm taking a look at fixing this. There are two potential solutions:
1. If user drags the seek cursor past the left side of the window, don't change the playback frame.
2. If user drags the seek cursor past the left side of the window, set the seek cursor to the leftmost position.

Solution 2 seems a bit harder but I'll try to do that one for now. Let me know if solution 1 is sufficient.

**Comment by jordan-zilch** [comment]
FYI that PR implements solution 2

**Comment by jordan-zilch** [comment]
I just found a related bug. If you hit the left arrow on your keyboard to seek past the beginning of the replay, the marker won't update position, but the game will load the initial savestate.

I'll fix that if I can figure out how the slider position is synced with targetFrameNum when you use the arrow keys
