### ISSUE TITLE
Linux: No Gecko Codes 

### ISSUE THREAD

**Issue by aribl** [project-slippi/Ishiiruka#128]
On a fresh install, no Gecko Codes show up.
I've verified that the Melee ISO hash is correct and that I'm actually running the Slippi Dolphin build.

Unsure if related (might need a separate issue), but icons seem to be missing:
![image](https://user-images.githubusercontent.com/1240516/87267394-71a74d80-c47c-11ea-8285-cf9729acf694.png)

**Comment by lytedev** [comment]
I'm also seeing this issue.

**Comment by NikhilNarayana** [comment]
This is fixed already in our linux-update branch for AppImages. If you build on your own then you need to copy Overwrite to the right place.
