### ISSUE TITLE
Can't navigate menu on startup

### ISSUE THREAD

**Issue by Kethku** [project-slippi/Ishiiruka#131]
This may be the wrong place to ask this...

I built dolphin from scratch but noticed that the slippi netplay features weren't enabled and the gecko codes were not available in the properties for my melee rom.

So I then cloned and built the slipp-ssbm-asm repository and copied the Output/Netplay/GALE01r2.ini file over the one I found in the Ishiiruka Data/Sys/GameSettings directory. 

This only sorta worked. Now when I run the game I get the 3 menu items, but no text shows up and if I do anything other than press A, the game will freeze and pop this message: "Invalid read from 0x3220270f, PC = 0x803a8a3c"

![image](https://user-images.githubusercontent.com/3323631/87391065-ea7ed600-c55e-11ea-931e-a667308d8581.png)

I suspect that I am missing a step to test slippi, but I didn't see any docs indicating as such. Maybe I missed something? Help would be appreciated.

**Comment by NikhilNarayana** [comment]
Please join the discord for dev setup support.

You likely didn't put Slippi in slot B and didn't copy the overwrite folders.
