### ISSUE TITLE
This application "Dolphin" cannot be opened on OSX 10.5.5

### ISSUE THREAD

**Issue by DustinAlandzes** [project-slippi/Ishiiruka#138]
I downloaded https://github.com/project-slippi/Ishiiruka/releases/download/v2.2.0/FM-Slippi-2.2.0-Mac.zip on Catalina/10.5.5 and got "This application 'Dolphin' cannot be opened".
<img width="422" alt="image" src="https://user-images.githubusercontent.com/5882512/87608253-043a2d80-c6c5-11ea-8bd5-0dce04a0102b.png">

However I could get this artifact from github actions running:
https://github.com/project-slippi/Ishiiruka/suites/919726534/artifacts/11212399

maybe not high priority, but could be fixed by just replacing the release build on slippi.gg

**Comment by NikhilNarayana** [comment]
We plan on fixing this soon so i'll leave this open until we do.

**Comment by NikhilNarayana** [comment]
This has been fixed basically. No more chmod, just move the Dolphin.app to Applications after unzipping.
