### ISSUE TITLE
Controller no longer responding after update

### ISSUE THREAD

**Issue by Grantismo** [project-slippi/Ishiiruka#140]
Controller worked correctly with no issues prior to most recent update.
Older versions of faster melee and Slippi also continue to work without issue.

Here's what I've tried so far:
* Installed both libusb-win32 (v1.2.6.0) and libusbK (v3.0.7.0), but no luck.
* Tried two different controllers.
* Restarted machine
* Rebooted Slippi
* Verified adapter is detected w/ a poll rate ~ 13kHz

Any ideas?

**Comment by NikhilNarayana** [comment]
Please use the support channels for questions.

Your adapter should not be polling at 13kHz, it should be around 125hz. Also use WinUSB
