### ISSUE TITLE
Attempting to play certain alt characters crashes for both players

### ISSUE THREAD

**Issue by schmooblidon** [project-slippi/Ishiiruka#148]
Giga-Bowser will work if player 2, otherwise will crash dolphin for both players.
Sopo works fine as either player.
Wireframes will always crash.

Not tested by me:
Hands, ive heard they always crash
Sandbag ?

**Comment by NikhilNarayana** [comment]
We intend on preventing users from picking any options outside of 26 characters that are tournament legal. I'll leave this issue up until we make that happen.

**Comment by NikhilNarayana** [comment]
Fixed in 54b7318bb768ad0e92571f24dbc85fccbfad3e03
