### ISSUE TITLE
macOS version is indistuingishable from the 'real' Dolphin

### ISSUE THREAD

**Issue by core-code** [project-slippi/Ishiiruka#158]
hello there,

we are trying to add support for your app inside our MacUpdater but it seems there is no single thing that could be used to distuingish Slippi-Dolphin from the real/stock/upstream Dolphin.

CFBundleIdentifier, and all other values in the Info.plist file are exactly the same as 'Dolphin'. even the icon is the same!

is it possible to change *something* in your app so it can actually be recognized (by humans and other apps or the operating system) that this is not just plain Dolphin but Slippi-Dolphin?

technically the 'right' thing would probably to change your 'CFBundleIdentifier' to an unique value as per Apple's guidelines.

thanks!

**Comment by core-code** [comment]
or add something to 'NSHumanReadableCopyright'

**Comment by NikhilNarayana** [comment]
https://github.com/project-slippi/Ishiiruka/pull/153

already done for our next release

**Comment by core-code** [comment]
awesome, thanks
