### ISSUE TITLE
Compiling with Raspberry Pie 4 ARM64 CPU...

### ISSUE THREAD

**Issue by nokkkkkk** [project-slippi/Ishiiruka#167]
Hi Guy's !

Here is the short story : I'm building a smash melee box with Raspberry pie 4 - 8gb of memory.

Don't say it's impossible I DID IT BUT !

PROS:
I can compile with CMAKE :
Dolphin and run it with smash(playable)
TINOB Ishiruka run with smash and reallly playable.

PROBLEMS :
Unfortunately the version I need to compile to play online with smash ladder and tournament is : https://github.com/project-slippi/project-slippi don't work...

I've been trying to compile it and got as far as 99% of compilation adding libs..tweaking code... etc...I got really far actually....but cant run it.

Anybody know...WHAT IS the major change that as been done on developing DOLPHIN that makes it run perfect on RaspberyPi4 with ARM64 ARCH CPU...That SLIPPY BRANCH never got to change: that makes it not working and compiling On ARM64 CPU.

Thanks a lot !

Just so you know I did solve a lot about ARM64 CPU as it would not even start the compilation....

PLEASE HELP ! :0) I've been trying for 6 months and about to surrender ! :)

**Comment by NikhilNarayana** [comment]
This is not something we intend on looking into. We know building on ARM is broken in this repo.
