### ISSUE TITLE
Marth back throw on Falco caused a semi-freeze glitch

### ISSUE THREAD

**Issue by hounvs** [project-slippi/Ishiiruka#173]
I've never seen this before so I assume it's a Slippi bug. Falco's animation froze and he started sliding around when I used back throw. I was already charging forward smash by the time I realized or I would have left him to see what happened.

Video [here](https://youtu.be/qFr0qX7z1Gw) and SLP replay [here](https://github.com/project-slippi/Ishiiruka/files/5019241/Game_20200803T181908.zip).

**Comment by NikhilNarayana** [comment]
This is an emulation bug that has been around for a long time.

https://medium.com/project-slippi/fighting-desyncs-in-melee-replays-370a830bf88b

Read the Dolphin Animation Freeze section
