### ISSUE TITLE
Direct Connection won't connect to opponent who is on the LAN connection

### ISSUE THREAD

**Issue by xSpikeisDEADx** [project-slippi/Ishiiruka#178]
I am trying to play Slippi rollback with my brother who lives within the same house hold as me. We search for eachother using our codes, it sits on searching for a while until it changes to connecting, then fails and reverts back to searching. We tested with 1 of us using a VPN to simulate being on another wifi and it instantly worked. Is there a way to play through LAN with Slippi?

**Comment by NikhilNarayana** [comment]
this fails because your network doesn't support NAT loopback (also called hairpinning). We can't really fix this on our end.

**Comment by k1r0s** [comment]
@NikhilNarayana is this related? https://www.youtube.com/watch?v=BwY6fnJOgUI I'm facing the same but we're on different networks.

if yes, are there any configurations in the router that the user has to be aware of? thx
