### ISSUE TITLE
"Render to Main Window" doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by kevinsung** [project-slippi/Ishiiruka#183]
Steps to reproduce:
1. Clone the slippi branch
2. Execute `./build-linux.sh playback`
3. Attempt to play a SLP file, e.g.
```
./dolphin-emu -i INPUT_FILE -b -e ISO_FILE
```
Result:
The following window pops up. That's it. No playback.
![Screenshot from 2020-08-16 20-10-46](https://user-images.githubusercontent.com/4296166/90590771-38a67b00-e196-11ea-803f-b27bb833001e.png)

I'm using g++ version 7.5.0.

**Comment by kevinsung** [comment]
I'll try it with a newer gcc version and report back.

**Comment by kevinsung** [comment]
I tried gcc/g++ version 10.1.0 and got the same problem.

**Comment by kevinsung** [comment]
Ok after discussing with Nikki, we established that the issue is that the "Render to Main Window" graphics option doesn't work for me.

**Comment by NikhilNarayana** [comment]
I don't think this is an issue we are going to worry too much about for Ishiiruka.
