### ISSUE TITLE
Error relating to gnutls on slippi appimage startup.

### ISSUE THREAD

**Issue by brandon-dodds** [project-slippi/Ishiiruka#187]
On a fresh Ubuntu 20.04.1 lts, this shows whenever I load the appimage.
`/tmp/.mount_Slippi4zFPMy/usr/bin/../lib/libgnutls.so.30: version GNUTLS_3_6_3 not found (required by /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so`
Maybe it's a dependency issue?

The game seems to run fine offline and online. It just takes around 20 seconds to start the emulator.

**Comment by NikhilNarayana** [comment]
please use the discord for support questions.
