### ISSUE TITLE
If Slippi was shut down for whatever reason and had to take their matchmaking servers offline, would we still be able to use the rollback Melee version to connect with our friends?

### ISSUE THREAD

**Issue by Azim-Palmer** [project-slippi/Ishiiruka#191]
Via IP connect or something similar?

I already asked this question [here](https://github.com/project-slippi/Ishiiruka/issues/190) but it was closed without a reason.

**Comment by JLaferri** [comment]
We will not be addressing this. The source code is on GitHub so I'll let you figure out the rest.

**Comment by Azim-Palmer** [comment]
Thank you for the response @JLaferri - Sorry I've put you in an uncomfortable situation. I will try to find someone that isn't scared of the question.

**Comment by JLaferri** [comment]
It's not a problem that needs to be solved until it's a problem

**Comment by Vaporjawn** [comment]
bruh

**Comment by Azim-Palmer** [comment]
> It's not a problem that needs to be solved until it's a problem

Yeah I am humbly asking you to take a minute on that position. I reckon I can assume you're heavily in favour of maximising the chances that everyone can continue to enjoy Melee to the level that this project enables. So what's the project's weakest point?

A single, closed-source centralised server through which every player has to connect in order to play online feels like it's up there on the list of weak points. 

If I'm wrong here I'd love to be told why. Are you saying there's already a P2P option? That coding another backend would be trivial etc?

A P2P connect option means people will always be able to play online together, come what may.

**Comment by JLaferri** [comment]
I don't think you understand my point. I'm saying that if something like that ever happens (which I'm very focused on making sure it doesn't happen), it'll be pretty trivial to transition the system using the source code that will still be available.

That said, my focus is to worry on what actually matters: that is, the system working as effectively as possible.

So like I said: it's not a problem currently, and it can be addressed if it ever becomes a problem.
