### ISSUE TITLE
Add support for DSU Protocol to enable Project Slippi to work with BetterJoy

### ISSUE THREAD

**Issue by andrea-feather** [project-slippi/Ishiiruka#199]
The main Dolphin emulator implements DSU support, allowing it to listen to programs like BetterJoy which allow for easy use of joycons and other non-xinput controllers. Currently Project Slippi doesn't support this, making it much more tedious to get joycons to work in it.

**Comment by NikhilNarayana** [comment]
We've already decided on moving to mainline Dolphin in the future and we don't intend to port something like this backwards.
