### ISSUE TITLE
Building with ENABLE_HEADLESS=true fails

### ISSUE THREAD

**Issue by nathan-miller23** [project-slippi/Ishiiruka#209]
Hello! My project team is currently trying to train a reinforcement learning agent to play Melee, and have found the slippi modifications incredibly helpful for sending dolphin gamestate data to our agents. My issue, however, is that I would like to be able to simulate many environments in parallel, without having to render each one. It appears there is a `ENABLE_HEADLESS` cmake flag, but setting it to true causes the build to fail. I am able to successfully build the headless executable in vanilla dolphin. 

## Command to Reproduce
(run from project root directory)
```
mkdir build
cd build
cmake .. -DENABLE_HEADLESS=true -DLINUX_LOCAL_DEV=true
cmake ..
make -j 2
```

## Bug
Compilation fails with the following error:
```
In file included from /dolphin/dolphin_src/Source/Core/Core/HW/EXI_DeviceSlippi.cpp:32:0:
/dolphin/dolphin_src/Source/Core/DolphinWX/Frame.h:11:10: fatal error: wx/bitmap.h: No such file or directory
 #include <wx/bitmap.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Source/Core/Core/CMakeFiles/core.dir/HW/EXI_DeviceSlippi.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Source/Core/Core/CMakeFiles/core.dir/build.make:2463: recipe for target 'Source/Core/Core/CMakeFiles/core.dir/HW/EXI_DeviceSlippi.cpp.o' failed
make[1]: *** [Source/Core/Core/CMakeFiles/core.dir/all] Error 2
CMakeFiles/Makefile2:1271: recipe for target 'Source/Core/Core/CMakeFiles/core.dir/all' failed
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

## Expected behavior
Should build an executable `dolphin-emu-nogui` that allows for simulating the game without graphics rendering

## Other info
* OS: Ubuntu 18.04
* CMake version: 3.10.2
* Make version: 4.1

Looking at the build logs, it appears the issue stems from [here](https://github.com/nathan-miller23/Ishiiruka/blob/slippi/Source/Core/Core/HW/EXI_DeviceSlippi.cpp#L32). It appears the cmake flag deliberately disables the linking of the wxWidgets library, which causes an error when a header file tries to import it later on in the build. My questions are twofold:
1) is there an easy fix to build the headless executable with the slippi branch
2) If not, is there currently any plan to support the headless build in the near future?

I understand this feature is most likely irrelevant to the gaming community, but it would be invaluable to the research community!

**Comment by NikhilNarayana** [comment]
We will probably be able to build headless again when we move to mainline but for now we aren't going to worry about fixing this issue ourselves. I will leave this issue open in case a community member would like to step up and figure it out.

**Comment by nathan-miller23** [comment]
Thanks for the speedy reply! Is there currently any timeline for when the migration to mainline dolphin will be completed? Trying to determine if it would be worth it to attempt to fix the headless build on this fork.

**Comment by NikhilNarayana** [comment]
No exact timeline, but I also don't think it makes sense to support headless on ishiiruka.
