### ISSUE TITLE
Make Login instructions more clear for Linux users

### ISSUE THREAD

**Issue by pizzadude** [project-slippi/Ishiiruka#252]
I found out, by guessing, to place user.json in ~/.config/SlippiOnline/ since putting it in the same directory as the AppImage doesn't work. The slippi website says to put it in the same directory as the EXE. It only works if user.json is in ~/.config/SlippiOnline/ which I had to find out myself, as I found no information online about this.

The slippi website should note this for Linux users.

I apologize if this is the wrong repo to report this issue.

**Comment by NikhilNarayana** [comment]
This is kind of the point of the webview login, it removes the need for most linux users (fedora notably has some issues) to deal with this issue. I will say this is a fairly low priority thing to fix and we do intend on removing the manual user.json step entirely from the flow in the near future.

**Comment by pizzadude** [comment]
I use Fedora KDE and before I found out where to place the user.json, when I clicked login in the game the emulator crashed. What's the webview login? Is it "Slippi Launcher"?
