### ISSUE TITLE
Unable to launch new appimage on Fedora

### ISSUE THREAD

**Issue by twiclo** [project-slippi/Ishiiruka#283]
Getting this error when trying to run the new AppImage on Fedora 32. A friend on Fedora 34 is having the same problem

```
This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
```

I have `gdk-pixbuf2-devel` and `gdk-pixbuf2` installed and up to date. We tried running `gdk-pixbuf-query-loaders-64 > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache` and `gdk-pixbuf-query-loaders-32 > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache` to no avail

**Comment by g4stly** [comment]
I got the same error.

I along with someone else in the slippi discord were able to repair it by replacing the /usr/share and /usr/lib directories in a 2.3.1 app image with the ones from a 2.3.0 app image.

Download both a 2.3.0 and a 2.3.1 version of the slippi app image.
Extract both with `./filename.AppImage --appimage-extract`.

That'll create a `squashfs-root` directory. 

Just move the `squashfs-root/usr/lib` and `squashfs-root/usr/share` from the extracted 2.3.0 into the extracted 2.3.1 folder, then use appimagetool (download here https://appimage.github.io/appimagetool/) to rebuild an appimage from the 2.3.1 directory.

**Comment by lararosekelley** [comment]
Perhaps this is a different issue, but I'm on Fedora 34 as well, and where I get hung up is that the launcher will run, and I can open/configure Dolphin from it, but when I click "Play" it will launch the Melee ISO but then crash after a few seconds. Have tried switching between OpenGL and Vulkan to no avail.

**Comment by Hnasar** [comment]
There's a new issue on Fedora 35, with a workaround: #323

Perhaps this should just be closed because it's old.
