### ISSUE TITLE
Unable to Log-in

### ISSUE THREAD

**Issue by gudenau** [project-slippi/Ishiiruka#288]
When launching Slippi and selected the "Log-in" button Dolphin freezes for a moment before being killed from a breakpoint trap with a corresponding core dump.

Terminal log:

    $ ./Slippi_Online-x86_64.AppImage
    
    (AppRun.wrapped:27937): Gtk-CRITICAL **: 21:36:44.534: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
    
    (AppRun.wrapped:27937): Gtk-CRITICAL **: 21:36:44.589: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
    
    ** (AppRun.wrapped:27937): ERROR **: 21:37:23.096: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
    Trace/breakpoint trap (core dumped)

From what I understand of AppImages is this library should be part of the image, that should fix the issue I am having here.

Slippi version: 2.3.1 (cf8a02885aca50b11c5c4d56d493ae565b629184)
Linux version: 5.10.42 LTS
CPU: i7-9750H
GPUs: GTX 1650 Max-Q, UHD Graphics 630
Distro: Arch

(I tried to record a video but the OBS package just happens to be broken right now)

**Comment by NikhilNarayana** [comment]
Please use our discord (linked on https://slippi.gg) for support.

**Comment by gudenau** [comment]
The fix was to install a single package: `webkit2gtk`
