### ISSUE TITLE
Show Frame Index option does not work

### ISSUE THREAD

**Issue by cnkeats** [project-slippi/Ishiiruka#289]
## Expected Behavior
Frame index should show in top left during replays (#276)

## Current Behavior
Frame index does not show in top left during replays

## Steps to Reproduce
1. Launch a replay
2. Toggle Show Frame Index

## Environment
Windows

</br>
</br>

I will likely be able to take a look at this, but I am creating the bug report for tracking.

**Comment by NikhilNarayana** [comment]
I can't reproduce this, are you sure you have `On-Screen Display Messages` enabled?
