### ISSUE TITLE
Replays not saving after 2.3.2 update

### ISSUE THREAD

**Issue by jsj1027** [project-slippi/Ishiiruka#311]
## Expected Behavior
After finishing a game longer than 30 seconds, a replay file is saved to the set folder. 

## Current Behavior
No replay file is saved. 
My replays since 8/10 are not saved. They seem to be completly lost. 
Extemely sad right now because I've been playing the best Melee of my life recently and I don't have the files to watch and learn from :(

## Steps to Reproduce

1. Play any unranked game
2. Check replay folder
3. No replay found 
4. Check set replay save folder to verify its the right location. 
5. Confirm it is. And be sad because the replay is not there :/

## Environment
Windows 10 latest update? Sorry doing this on my phone

**Comment by cnkeats** [comment]
Be sure you are checking the replay folder selected in Dolphin config, NOT the launcher settings. Launcher settings currently do not update Dolphin.

**Comment by jsj1027** [comment]
> Be sure you are checking the replay folder selected in Dolphin config, NOT the launcher settings. Launcher settings currently do not update Dolphin.

This was it, thank you.
