### ISSUE TITLE
bug: Players can match with themselves

### ISSUE THREAD

**Issue by gregorymarco** [project-slippi/Ishiiruka#316]
I entered, exited, then re-entered the matchmaking queue quickly and [this happened](https://www.reddit.com/r/Slippi/comments/pojtnz/managed_to_queue_into_myself/). 
\user\logs\dolphin.log is empty. I'm not sure what supporting info to provide. 

Not consistently/easily reproducible.

**Comment by DocFreeman** [comment]
I had this happen once yesterday. Just wanted to state this bug is still scurrying around.

**Comment by NikhilNarayana** [comment]
this issue is server side and tracked over there so i'm closing this one
