### ISSUE TITLE
Rumble continues after L-R-A-Start

### ISSUE THREAD

**Issue by beaudry** [project-slippi/Ishiiruka#327]
If either player stops the game with an L-R-A-Start, the controller will keep rumbling at the same force as it was at the time of the input.

## Expected Behavior

The controller stops rumbling when going back to the CSS screen.

## Current Behavior

The controller keeps rumbling during the CSS screen.

## Steps to Reproduce

1. Enable rumble
2. Start a game
3. Self-destruct
4. L-R-A-Start while hitting a blast zone (it's the most consistent way triggering the rumble)
5. The controller will keep rumbling

## Environment
Windows 10
MayFlash Adapter

**Comment by beaudry** [comment]
> If either player stops the game with an L-R-A-Start, the controller will keep rumbling at the same force as it was at the time of the input.
> 
> ## Expected Behavior
> The controller stops rumbling when going back to the CSS screen.
> 
> ## Current Behavior
> à
> The controller keeps rumbling during the CSS screen.
> 
> ## Steps to Reproduce
> 1. Enable rumble
> 2. Start a game
> 3. Self-destruct
> 4. L-R-A-Start while hitting a blast zone (it's the most consistent way triggering the rumble)
> 5. The controller will keep rumbling
> 
> ## Environment
> Windows 10

**Comment by beaudry** [comment]
I just went and look around, and there's [talk about this in the asm repo](https://github.com/project-slippi/slippi-ssbm-asm/issues/44), although the issue is still open, but there's a PR that's been merged 🤷‍♀️

**Comment by JLaferri** [comment]
Addressed by https://github.com/project-slippi/slippi-ssbm-asm/pull/85
