### ISSUE TITLE
Dolphin crashes with "Failed to allocate below the 2GB boundary" errors

### ISSUE THREAD

**Issue by VitamintK** [project-slippi/Ishiiruka#339]
I used to experience issue #160. I downloaded the newest Faster Melee - Slippi Dolphin (2.4.0) and now I get a very similar error to before:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/1139798/153953591-db7a381d-37c7-4051-8d73-28c6b33355b5.png">

and it still crashes.  Figured I'd open an issue, but if this is actually just the same bug as #160, then feel free to close.

## Environment

Mac OS Big Sur (11.4), Macbook Pro 16-inch, 2019

Slippi Launcher Version 2.1.13 (2.1.13)
Faster Melee - Slippi Dolphin 2.4.0

**Comment by ryanmcgrath** [comment]
This is still the same bug, the error message is just noting a different point of failure. At this point it's pretty much a `won't-fix`, as anything that can be done to alleviate or lessen the impact has been done.

I would be curious if it still persists after a restart + redownload + try with nothing else open in the background, but that's going more into `#mac-support` territory - the Slippi Discord is a better place for that exercise.
