### ISSUE TITLE
Update to Apple Silicon Native Dolphin on MacOS

### ISSUE THREAD

**Issue by marcelroed** [project-slippi/Ishiiruka#354]
## Expected Behavior
Ishiiruka should perform roughly the same as vanilla Dolphin.

## Current Behavior
Running on the latest MacBook Pros results in laggy performance, often with the red indicator text showing "Your computer is running slow and impacting the performance of the match". The game is noticeably more sluggish than running it using native Dolphin.

## Steps to Reproduce

1. Run Slippi netplay on any M1 Mac
2. Compare with Dolphin running Melee on M1 Mac, which runs lag-free on any resolution

## Environment
Late 2021 MacBook Pro with M1 Pro, latest Slippi/Ishiiruka version 2.4.0 (not Apple Silicon native).
Compared to Dolphin Beta version 5.0-16380 (Apple Silicon native).

## Some Questions
From what I understand this would require rebasing Ishiiruka off of a later version of Dolphin, right?
What needs to be done for that to be possible?
Would it maybe also be possible to rebase the changes that lead to Apple Silicon support in the current beta versions of Dolphin on top of Ishiiruka?

Thanks!

**Comment by FluentCoding** [comment]
There is already ongoing work to move Slippi from Ishiikura to Mainline which would also include native M1 support.

**Comment by NikhilNarayana** [comment]
Ishiiruka is too far gone to be rebased onto mainline dolphin. This will be a thing once we release our mainline version.

**Comment by ryanmcgrath** [comment]
>Would it maybe also be possible to rebase the changes that lead to Apple Silicon support in the current beta versions of Dolphin on top of Ishiiruka?

Just for anybody who drives by and see this - I did in fact experiment with this some time ago, and it's fundamentally not possible due to the way that Ishiiruka works (being a much older fork of Dolphin) coupled with changes to macOS over the years.

**Comment by ryanmcgrath** [comment]
If I don't get to it this week, feel free to ping me here again - I've been crazy busy unfortunately so I'll have to fit it in somewhere is all.

**Comment by milesoncken** [comment]
Are us m1 boys SOL then?

**Comment by NikhilNarayana** [comment]
This issue has been addressed. M1 also works fine with Rosetta. if you need help ask in our discord for support @Buna101
