### ISSUE TITLE
Desync Triggers Every Game

### ISSUE THREAD

**Issue by cgrinker** [project-slippi/Ishiiruka#364]
Desync detector displays every game. Games still playing as normal. 

## Environment
Windows Version10.0.19043 Build 19043
Processor	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 Mhz, 4 Core(s), 8 Logical Processor(s)

[Game_20220901T130621.zip](https://github.com/project-slippi/Ishiiruka/files/9473084/Game_20220901T130621.zip)

**Comment by cgrinker** [comment]
There doesn't seem to be any more hitches then I normally play with but now there's giant text in the middle of the screen that makes it pretty hard to concentrate

**Comment by JLaferri** [comment]
Read this thread:

https://twitter.com/Fizzi36/status/1565416973374291969?s=20&t=bajDXNvs8bH_QqGegBXaBg
