### ISSUE TITLE
Crash on Arch Linux

### ISSUE THREAD

**Issue by pavethem** [project-slippi/Ishiiruka#382]
Running Gnome 44 under X11 on Arch, when starting Melee, Slippi immediatly crashes with:
38763 IOT instruction (core dumped)
This is on OpenGL.

## Environment
Latest packages

**Comment by pavethem** [comment]
Some more information on this crash:

This is the complete error message: 

> terminate called after throwing an instance of 'std::logic_error'
> what():  basic_string: construction from null is not valid
>[1]    46073 IOT instruction (core dumped)  ./build/Binaries/dolphin-emu

coredumpctl output:
[coredump.txt](https://github.com/project-slippi/Ishiiruka/files/11509349/coredump.txt)
This is from a fresh build, but the same happens on the official appimage.

The crash does not seem to be tied to Gnome after all (also happens on KDE)
The crash also does not seem to be tied to the nvidia driver (also happnes on intel iGPU)

**Comment by HamletDuFromage** [comment]
AUR's dolphin-emu-git seems to have figured it out

https://aur.archlinux.org/cgit/aur.git/commit/?h=dolphin-emu-git&id=b1d7ef9008ba6162824cc57cf9ee70a17ee2e3e5

**Comment by pavethem** [comment]
Unfortunately your latest commit does not make a difference in regards to this bug report.
I believe the bug addressed in the AUR patch was related to building dolphin on Arch, but this has never been an issue for me.

**Comment by SirToffski** [comment]
I cannot replicate the crash on XFCE.

There's a similar error [here](https://github.com/flathub/com.mojang.Minecraft/issues/25), resolved by setting `LC_ALL`. Perhaps try launching the AppImage / binary like this:
```bash
LC_ALL=C /path/to/executable
```

**Comment by pavethem** [comment]
Strangely enough, I cannot reproduce this crash either anymore. Might have been a problem with a previous nvidia driver? Anyways, I think we can close this.
