### ISSUE TITLE
hi there!

### ISSUE THREAD

**Issue by lucasmz1** [project-slippi/Ishiiruka#411]
recently I've tried to buid dolphin can you help me ? https://github.com/lucasmz1/Dolphin_emu_Appimage this is my repository can you teach me how to do it ? mine is given error listdc++6 and I can't get away with it.
or teach me how to build your app since it's the same as dolphin.
please help me.

**Comment by NikhilNarayana** [comment]
https://github.com/project-slippi/Ishiiruka/blob/slippi/.github/workflows/pr-build.yml#L165

you can take a look at how our CI builds dolphin on Ubuntu 20.04, if you need further help then you can ask in our [discord](https://slippi.gg/discord)
