### ISSUE TITLE
When using multiple playback dolphins, every SlippiSpectateServer after the first fails to start

### ISSUE THREAD

**Issue by jmlee337** [project-slippi/Ishiiruka#419]
this is because there is no mechanism to try a different port then the default (there also doesn't appear to be any way to change the default):
https://github.com/project-slippi/Ishiiruka/blob/18ee3450ee1cfde20ada2547c4792dc863dcd075/Source/Core/Core/Slippi/SlippiSpectate.cpp#L281-L302

adding an Ishii command-line option to set the SlippiSpectateServer port would alleviate this problem

**Comment by vladfi1** [comment]
Note that you can set this in Dolphin.ini:
```
[Core]
SlippiEnableSpectator=True
SlippiSpectatorLocalPort=12345
```
