### ISSUE TITLE
Add the ability to disable replays and set replay directory path

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/Ishiiruka#42]
We want users to be able to go to the Config->GameCube settings page and be able to toggle replay saving and set their replay directory.

This is a bit of a tougher issue, so anyone wanting to take this on should be prepared to deep dive into the codebase.

**Comment by pacnetnetty** [comment]
Currently working on this.

**Comment by NikhilNarayana** [comment]
> Currently working on this.

Please reach out on discord in #dev-general if you need help
