### ISSUE TITLE
Build breaks after Cargo 1.79

### ISSUE THREAD

**Issue by pylasnier** [project-slippi/Ishiiruka#423]
Cargo 1.79 has changed behaviour where dashes are replaced with underscores in lib names, as listed in their [changelog](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-179-2024-06-13). This appears to have broken the Ishiiruka build by causing CMake to generate an incorrectly hyphenated arguments, with it failing at linking for not finding the `slippi_rust_extensions` lib. I have not tried to build for any version beyond Rust 1.79, but the linker argument generated (listed below) is still hyphenated in nightly.

## Expected Behavior
Build (normal behaviour with Cargo 1.78). `-lslippi_rust_extensions` with *underscores* is passed to the linker.

## Current Behavior
With Cargo 1.79, build fails with:
```
[100%] Linking CXX executable ../../../Binaries/dolphin-emu
/nix/store/qsx2xqqm0lp6d8hi86r4y0rz5v9m62wn-binutils-2.42/bin/ld: cannot find -lslippi-rust-extensions: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/build.make:1434: Binaries/dolphin-emu] Error 1
make[1]: *** [CMakeFiles/Makefile2:1426: Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```
where `-lslippi-rust-extensions` with *hyphens* is passed to the linker.

## Steps to Reproduce

1. Install `rustc` and Cargo with Rust version 1.79
2. Follow Ishiiruka build instructions

## Environment
NixOS, built in `nix-shell` environment.

**Comment by pylasnier** [comment]
A note that this Cargo change introduces swaps of hyphens and underscores for the lib file in many places throughout the generate CMake files, and simply changing the linker argument back is not enough to fix the build.

**Comment by ryanmcgrath** [comment]
Huh, it's likely a simple-ish fix of just [changing the crate name](https://github.com/project-slippi/slippi-rust-extensions/blob/1e9fbf11479e20cd07a75f67888c138c7893bc24/ffi/Cargo.toml#L2) to use underscores for consistency. It's not like it gets uploaded or distributed outside the project.

I'll see about poking at this over the weekend since the way Windows finds the lib is a bit custom.

(I don't suppose there's a way to force the Cargo 1.78 behavior anywhere, is there?)

**Comment by pylasnier** [comment]
> (I don't suppose there's a way to force the Cargo 1.78 behavior anywhere, is there?)

[This comment](https://github.com/rust-lang/cargo/pull/12783#issuecomment-1761370833) from the offending pull request implies that backwards compatibility is retained, but that isn't the case for Ishiiruka or even other projects, it seems.

> it's likely a simple-ish fix of just [changing the crate name](https://github.com/project-slippi/slippi-rust-extensions/blob/1e9fbf11479e20cd07a75f67888c138c7893bc24/ffi/Cargo.toml#L2) to use underscores for consistency.

This seems to be what other projects with similar failures are doing, though corrosion (which seems to be where the mismatch arises from) also [fixes this](https://github.com/corrosion-rs/corrosion/issues/501) in v0.5.0 without requiring a name change.

I can confirm that replacing all (non-URL) instances of `slippi-rust-extensions` with `slippi_rust_extensions` in the main repo and the Rust submodule (there's not many instances, only 2 total) builds successfully with Cargo 1.79.0 on Linux.

**Comment by pylasnier** [comment]
> I can confirm that replacing all (non-URL) instances of `slippi-rust-extensions` with `slippi_rust_extensions` in the main repo and the Rust submodule (there's not many instances, only 2 total) builds successfully with Cargo 1.79.0 on Linux.

I've written a small PR which adds these changes
