### ISSUE TITLE
Dolphin will segfault if the Slippi Device isn't in Slot B

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/Ishiiruka#47]
Right now we segfault if the Slot B device isn't set to Slippi. We haven't confirmed if this happens on only NTSC 1.02 Melee or all games.

**Comment by pacnetnetty** [comment]
GDB traced it to CFrame::ParseHotkeys. It might be caused by this line: https://github.com/project-slippi/Ishiiruka/blob/slippi/Source/Core/DolphinWX/Frame.cpp#L1295

Because there is no check for g_playback_status being a null pointer

**Comment by ehandal** [comment]
Ah, I didn't realize someone else was looking at this too. I found the same issue as @bhegde8.

I created PR #52 to fix the null pointer dereference.
