### ISSUE TITLE
Eaten Dashdance Inputs - Bisected r18 Regression

### ISSUE THREAD

**Issue by ghost** [project-slippi/Ishiiruka#53]
Changes made in 078aa1ef6e004506416fe590cd4a1455d543348c appear to cause eaten inputs for Marth's dashdance for me, both while mid-dash and occasionally causing difficulty starting the dashdance (just walks forward a little bit or turns around).

I know rollback's delay is supposed to be equivalent to 8 buffer on r18 1ef6f7bfc12e8566153054e6c964111da44f9125 which is supposed to be the most similar to crt, but it feels noticeably worse for me while playing against someone with a stable ~30 ms.

It's most easily noticeable for me when hosting a local netplay lobby at 8 buffer to use unclepunch and 20xx. I tested it on fresh downloads of r18, 2.0.0-2.0.3, and all the builds (clean builds) while bisecting using unclepunch L-cancel training with Marth on FD by spamming dashdance. Nice, quick, and controlled dashdance on r18 but the same inputs have me running off in a random direction on builds starting from 078aa1ef6e004506416fe590cd4a1455d543348c.

OS Name: Microsoft Windows 10 Home
Version: 10.0.19041 Build 19041
CPU: i7-6800k
GPU: Nvidia 1080 ti
Adapter: Official Switch Adapter (Zadig'd WUP-028 WinUSB (v6.1.7600.16385))
Controller: Smash 4 White - No electrical mods, good tests
Monitor: ASUS VG27AQ @ 144 hz

Nvidia Settings:
- Gsync Enabled for windowed and full screen mode

**Comment by NikhilNarayana** [comment]
Can you revert that commit and test?

**Comment by ghost** [comment]
Looks like it causes conflicts, might need to do it right at a 2.0.x rather than the most recent commit but there aren't tags for those so I'll have to look through the history. I'll see if a can resolve them later but I don't really know anything about the code base. 

On branch slippi
Your branch is up to date with 'origin/slippi'.

You are currently reverting commit 078aa1ef6.
  (fix conflicts and run "git revert --continue")
  (use "git revert --abort" to cancel the revert operation)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   Source/Core/DolphinWX/Frame.h
        modified:   Source/Core/DolphinWX/FrameTools.cpp

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   Source/Core/Core/HW/EXI_DeviceSlippi.cpp
        both modified:   Source/Core/Core/HW/EXI_DeviceSlippi.h
        both modified:   Source/Core/Core/HW/SI.cpp

**Comment by ghost** [comment]
Well, so far I've isolated the issue to Source/Core/Core/HW/SI.cpp 6128f8365c9b311be53e10e12a9cc4a204cbe11f.

All the conflicts were completely innocuous other than different values for ROLLBACK_MAX_FRAMES (7 vs 5) in EXI_DeviceSlippi.h, which I verified had no impact on the issue. So I did a partial revert where I only reverted the changes with an impact in SI.cpp, and it feels much better.

I haven't bothered trying to alter the remaining changes for a fix at all since I have basically no knowledge of the inner workings of this code.

**Comment by JLaferri** [comment]
The commit you linked, does it revert that section to what it was before?

**Comment by ghost** [comment]
Other than the bit of code here https://github.com/project-slippi/Ishiiruka/commit/078aa1ef6e004506416fe590cd4a1455d543348c#diff-b62f4664b164e36115c14f8f55559034R684, which is commented out in the current revision, yes, it reverts SI.cpp to 078aa1ef6e004506416fe590cd4a1455d543348c.

**Comment by JLaferri** [comment]
Gotcha, that should all be safe. You can probably just revert anything that references the `g_BButtonPressTime` variable. Mind doing that?

**Comment by JLaferri** [comment]
Afterwards feel free to submit the PR, I'll look it over and merge if it looks good.

**Comment by ghost** [comment]
C++ isn't my expertise but I can probably manage. These are the only references to `g_BButtonPressTime`:

```
./Source/Core/Core/HW/EXI_DeviceSlippi.cpp:76:extern u64 g_BButtonPressTime;
./Source/Core/Core/HW/EXI_DeviceSlippi.cpp:1959:        //      NOTICE_LOG(SLIPPI, "%llu", Common::Timer::GetTimeUs() - g_BButtonPressTime);
./Source/Core/Core/HW/SI.cpp:683:               g_BButtonPressTime = Common::Timer::GetTimeUs();
./Source/Core/Core/HW/SI.cpp:684:               ERROR_LOG(SLIPPI, "B Press: %llu", g_BButtonPressTime);
```

You just want me to rip that stuff out?

**Comment by JLaferri** [comment]
Yeah any reference to the variable and you can get rid of the commented code blocks that reference it too

**Comment by JLaferri** [comment]
Merged

**Comment by NikhilNarayana** [comment]
Did that PR fix the issue?

**Comment by ghost** [comment]
Yes, thank you both for working with me on it. Does this affect both rollback online and old netplay lobbies, or just old netplay lobbies? I haven't tried to test the changes with rollback online at all because I assumed it would only allow official release clients.

**Comment by NikhilNarayana** [comment]
> Yes, thank you both for working with me on it. Does this affect both rollback online and old netplay lobbies, or just old netplay lobbies? I haven't tried to test the changes with rollback online at all because I assumed it would only allow official release clients.

you can try playing with the latest commit, just no guarantees it won't desync.

**Comment by JLaferri** [comment]
@reinhard33 how were you able to confirm that this fixed your issue btw? Just testing it locally? Also do you have discord? would be easier to communicate more quickly there, feel free to DM after joining the Slippi Discord

**Comment by ghost** [comment]
I confirmed that this PR fixed the issue with the local netplay lobbies. I think the slowness online I mentioned in the first post was something else because I did my first direct connect with a friend on 2.0.3 with known good connections, and that was perfect.
