### ISSUE TITLE
Configuration for Linux AppImages is still affected by portable.txt

### ISSUE THREAD

**Issue by eigenform** [project-slippi/Ishiiruka#55]
Steps to repro:

1. Have an AppImage with configuration files in `~/.config/SlippiOnline`
2. `touch portable.txt` in the same directory as the AppImage

**Comment by ggliv** [comment]
I'm not able to reproduce this with the latest commit.

What I did:
1. Create a new, clean AppImage
2. Run the AppImage (~/.config/SlippiOnline created and populated)
3. Delete ~/.config/SlippiOnline and `touch portable.txt` in the same directory as the AppImage

~/.config/SlippiOnline is then remade like before.

Is there anything else I should be looking for or any other way I can test for this?

**Comment by eigenform** [comment]
Think this was a mistake on my end; I can't reproduce this now.
