### ISSUE TITLE
Emulator keeps crashing when it starts to run a game.

### ISSUE THREAD

**Issue by stvene3004** [project-slippi/Ishiiruka#56]
All it does is start to run and dissapear. I don't know why, but it keeps happening. I've tried changing all of my settings, but none of that work. The other builds of Dolphin work fine tho, even Ishiiruka, considering this was built off of that.

**Comment by ggliv** [comment]
This likely has to do with either not having a valid ISO or not having your Gecko codes enabled.
From some relevant Discord Dyno commands:
```
Make sure your ISO is valid by right clicking melee and going to Properties->Info and checking that the revision of Melee is #2.

Compute the MD5 hash of the ISO by clicking the Compute button and make sure it matches 0e63d4223b01d9aba596259dc155a174.
```

```
If you don't have the right codes enabled for melee you will not be able to play online. To find the codes enabled, right click on melee and then go to Properties->Gecko Codes 

Make sure the following codes are enabled:

Faster Melee Netplay Settings
Normal Lag Reduction
Enable OSReport Print on Crash (1.02)
Slippi Recording
Slippi Online
```
If you are still having trouble after working out those potential issues, consider joining the Slippi Discord and asking for help in the support-and-bugs channel, then come back here if it seems like it is a code issue.

https://discord.gg/pPfEaW5

**Comment by NikhilNarayana** [comment]
The issues section is for actual bug reports, please do what ggliv said
