### ISSUE TITLE
Dolphin on 2.1.0 Update Opens and Closes Instantly

### ISSUE THREAD

**Issue by gabrielchan** [project-slippi/Ishiiruka#84]
**Summary**
When user attempts to open Dolphin from Windows UI, it opens then closes instantly..

- There are no reports or logs generated in User/Logs
- Running Dolphin.exe -d or Dolphin -l still creates the same issues with no logs or stack trace created

**Steps to Reproduce**

1.  Open Dolphin

**Expected Results**
Dolphin executable opens and remains open for user interaction

**Actual Results**
Dolphin immediately closes

**Mitigations Attempted**

- Restarted Computer
- Re-installed Slippi
- Enabled / Disabled Fast Boot
- Un-installed and Re-installed VC 2019 Redist

**Details on reporter computer**
OS: Windows 10 v1909 build 18363.900

**Comment by NikhilNarayana** [comment]
Is this still occuring on 2.1.1? I don't think the steps are actionable in any way and the issue might be a product of your specific setup.
