### ISSUE TITLE
Replay metadata is not generated when a netplay match is ended by local or remote LRAS

### ISSUE THREAD

**Issue by carbonXIII** [project-slippi/Ishiiruka#88]
[generateMetadata()](https://github.com/project-slippi/Ishiiruka/blob/slippi/Source/Core/Core/HW/EXI_DeviceSlippi.cpp#L270) does not get called if a match is ended via LRAS (by either player). This generates replays without dates, player names, etc.

Presumably, this is due to the new changes to pausing. I don't think ending via LRAS generates a `CMD_RECEIVE_GAME_END` as it did in 2.0.3, so the file is not closed properly with `writeToFile(.... ,"close");` This is the same effect as if Dolphin had crashed.

### Steps to reproduce
1. Enter an unranked or direct connect match
2. Quit via L+R+A+Start
3. View the replay metadata in the desktop app or slp-parser-js

**Comment by NikhilNarayana** [comment]
I'm failing to recreate this bug on 2.1.1, maybe it is already fixed?

**Comment by carbonXIII** [comment]
I was already on 2.1.1 when I did my testing, so perhaps there was a configuration issue on my end. After a clean reinstall I can no longer recreate the issue. I probably should have done that to begin with :sweat:
